@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml
title Mister, Mister 
mainframe characters


:Yahya Bas: as yahya <<protagonist>> $male_protagonist

:Estella Stevens: as mother $female
:Mother Sadaf: as sadaf $female
:Mother Miriam: as miriam  $female

sadaf --> mother : doula 
miriam --> mother : doula 

sadaf ---> yahya : other mother 
miriam ---> yahya : other mother 

:Sisi Gamal: as uncle $male
uncle --> yahya : uncle 


mother --> yahya : mother 

:Marwan Bas: as father $male

yahya <-- father : father 

(refuge center for women of low to no means) as house <<institution>>

:Mother Aneesa: as aneesa $female

aneesa --- house

house --- mother 
house -- sadaf 
house -- miriam
house -- uncle

:Mother Shahnaz: as shahnaz $female
:Mother Sofiyya: as sofyiia $female

shahnaz -- house : second floor
sofyiia -- house : second floor

shahnaz <-> sofyiia : together

:Mother Fareeda: as fareeda $female 

fareeda -- house : down the hall

:Fatima: as fatima $female 
fatima --> fareeda : sister 

fatima .... house:  vanished long ago
note on link: if ever existed

:Faris: as faris $male
faris --> aneesa: uncle

(mosque) <<institution>>

:Imam Ghulam: as imam $male 

(boat) <<event>> 

father -- boat 
uncle -- boat 
:Hamidullah Sayed: as hamidullah $male
boat -- hamidullah 

imam -- mosque 

:Abdi: as abdi $male
:Anas: as anas $male 

mosque -- abdi 
mosque -- anas

(School) <<institution>>

yahya -- (School)

:Craig: as bully $male

(School) -- bully : bully

@enduml