@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml
title Mister, Mister 
mainframe characters


:Yahya Bas: as yahya <<protagonist>> $male_protagonist

:Estella Stevens: as mother $female
:Mother Sadaf: as sadaf $female
:Mother Miriam: as miriam  $female

sadaf --> mother : doula 
miriam --> mother : doula 

sadaf ---> yahya : other mother 
miriam ---> yahya : other mother 

:Sisi Gamal: as uncle $male
uncle --> yahya : uncle 


mother --> yahya : mother 

:Marwan Bas: as father $male

yahya <-- father : father 

(refuge center for women of low to no means) as house <<institution>>

:Mother Aneesa: as aneesa $female

aneesa -- house

house --- mother 
house -- sadaf 
house -- miriam
house -- uncle

:Mother Shahnaz: as shahnaz $female
:Mother Sofiyya: as sofyiia $female

shahnaz -- house : second floor
sofyiia -- house : second floor

shahnaz <-> sofyiia : together

:Mother Fareeda: as fareeda $female 

fareeda -- house : down the hall

:Fatima: as fatima $female 
fatima --> fareeda : sister 


:Faris: as faris $male
faris --> aneesa: uncle

(mosque) <<institution>>

:Imam Ghulam: as imam $male 

(boat) <<event>> 

boat -- father
uncle -- boat 
:Hamidullah Sayed: as hamidullah $male
boat - hamidullah

imam -- mosque

:Abdi: as abdi $male
:Anas: as anas $male 

mosque -- abdi
mosque -- anas

(School) <<institution>>

yahya -- (School)

:Craig: as bully $male

(School) -- bully : bully 

:John Muhammad: as muhammad $male 
muhammad -> miriam : husband

(School) -- imam  : sponsor

:Mrs Chow: as nurse $female
(School) -- nurse   : nurse 

:Wayne: as bully2 $male 
:Gavin: as bully3 $male 

(School) -- bully2 : bully 
(School) -- bully3 : bully 

(ibn Rabah school) as school2 <<institution>> 

(brorher-peers) as peers <<group>> 

yahya -- school2 

school2 -- peers 

:Ibrahim: as ibrahim $male 
:Hass: as hass $male 
:Moazzam: as moazzam $male 

peers -- ibrahim: gab 
peers -- hass : entrepreneur 
peers -- moazzam : seer 

:Samir: as samir $male 
school2 -- samir : Salafi 

:Abdallah: as abdallah $male

father <-- abdallah : friend 

:Zenab: as zenab $male 

ibrahim <-- zenab : volunteer 

@enduml