@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml


'============== поехали ================
title Mansions of the Moon
mainframe characters


'Dukha I

:Yasodhara: <<protagonist>> as she

:Siddhartha: <<ex>> as budda

budda --> she : husband

:Prajapati: as aunt
she <- aunt : aunt

:Rahula: as fetter
she <-- fetter : son
fetter --> budda  : son

:Devadatta: as devadatta

she <-- devadatta : brother

' Froth on the River

:Pamita: as mother 

mother --> she : mother 

:Dandapani: as father 

father --> she : father 

:Maha Kosala: as overlord 

father <-- overlord : overlord

:Prajapati: as aunt

aunt --> budda : stepmother
aunt --> father : sister

:Sundari Nanda: as halfsister 

aunt <-- halfsister : daughter

:Suddhodana: as abuser 

:Pasénadi: as regent 
regent --> overlord : regent 


:Bandhula: --> regent : closest friend 
:Karayana: --> regent : closest friend 

:Bandhula: --> :Karayana: : uncle 

:Kusuma: as courtesan 

regent --> courtesan : patron 

:Ubbiri: --> regent : wife 

:Bimbisara: as emperor 

:Ubbiri: --> emperor : sister 

:Amitodhana: --> mother : other brother 

:Mahanama: --> :Amitodhana: : son 

:Suddhodana: as abuser 

:Mahanama: --> abuser : successor 

abuser --> budda : father 

she --> :Mitta: : orphaned spinster cousin

:Sumana: <<ex>> 
:Sumana:  --> abuser : concubine 

:Upasama: --> abuser : concubine 

:Ananda: --> she : cousin 
(Takkasila) <<location>> 
(Takkasila)  -- :Ananda: : exile

:Anuruddha: --> she : favorite cousin 
:Amitodhana: --> :Anuruddha: : father 
:Mrgi: -- (Takkasila) : exile

:Mrgi: --> :Anuruddha: : mother 
:Amitodhana: <-- :Mrgi:  : first wife

:Vimala: 
note bottom: courtesan


(Takkasila) -- :Mendaka: 
:Mendaka: --> :Ananda: : master 

:Ambapali: 
note top: famous curtesan 

:Vimala: <-- :Visaka:  : adopted daughter

'(Kapilavastu) <<location>>

'(Kapilavastu) -- abuser

':Vimala: -- (Kapilavastu)

' froth on the river 

(Mudgala) <<location>> as gala 

budda -- gala : rashtrika 

gala -- :Vagantha:  : gambojaka 

:Vagantha: <-- :Rupasiri: : wife 

overlord --> regent : father 

:Nagamunda: --> :Amitodhana: : slave 
:Vasabha: --> :Nagamunda: :daughter 
:Vasabha: --> :Mahanama: :daughter 

' Dukkha II

budda <-- :Channa: : charioteer

' A Woman Eaten and Eaten
'(Kapilavastu) -- :Sonanda: : gatekeeper

note "widowed relatives" as w

:Tissa: .. w
:Utara: .. w

budda <-- :Maya: : mother

:Sanga: --> abuser : concubine 
 :Visaka: --> abuser  : concubine

'(Kapilavastu) -- :Jatila: : Mahasetthi
budda <-- Jatila : Mahasetthi
'(Kapilavastu) -- :Rakkha: : old brahmin

:Anuruddha:  --> :Bhaddiya:  : friend
:Kimbila: <-- :Anuruddha: : friend
:Kaligodha: --> :Bhaddiya: : mother 

:Jatila: <-- :Sirima: : wife 

:Jatila: <-- :Alara Kalama: : guest 

(woman quarters) <<institurion>> as serpentary

serpentary -- :Tissa:
serpentary -- :Utara:
serpentary -- :Sanga:
serpentary -- :Visaka:
:Mitta: -- serpentary

serpentary -- :Sumana:
serpentary -- :Upasama:


she -- serpentary
aunt -- serpentary : leader

:Amitodhana: -> abuser : brother

:Mantani: --> :Mahanama: : daughter

@enduml