@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml


'============== поехали ================
title Mansions of the Moon
mainframe characters


'Dukha I

:Yasodhara: <<protagonist>> as she

:Siddhartha: <<ex>> as budda

budda -> she : husband

:Prajapati: as aunt
she <- aunt : aunt

:Rahula: as fetter
she <-- fetter : son

:Devadatta: as devadatta

devadatta --> she : brother

' Froth on the River

:Pamita: as mother 

mother --> she : mother 

:Dandapani: as father 

father --> she : father 

:Maha Kosala: as overlord 

overlord --> father : overlord 

:Prajapati: as stepmother 

stepmother --> budda : stepmother 
stepmother --> father : sister 

:Sundari Nanda: as halfsister 

halfsister --> stepmother : daughter 

:Suddhodana: as abuser 

:Pasénadi: as regent 
regent --> overlord : regent 


:Bandhula: --> regent : closest friend 
:Karayana: --> regent : closest friend 

:Bandhula: --> :Karayana: : uncle 

:Kusuma: as courtesan 

regent --> courtesan : patron 

:Ubbiri: --> regent : wife 

:Bimbisara: as emperor 

:Ubbiri: --> emperor : sister 

:Amitodhana: --> mother : other brother 

:Mahanama: --> :Amitodhana: : son 

:Suddhodana: as abuser 

:Mahanama: --> abuser : successor 

abuser --> budda : father 

:Mitta: --> she : orphaned spinster cousin 

:Sumana: <<ex>> 
:Sumana:  --> abuser : concubine 

:Upasama: --> abuser : concubine 

:Ananda: --> she : cousin 
(Takkasila) <<location>> 
(Takkasila)  -- :Ananda: : exile

:Anuruddha: --> she : favorite cousin 
:Amitodhana: --> :Anuruddha: : father 
(Takkasila) -- :Mrgi: : exile 

:Mrgi: --> :Anuruddha: : mother 
:Mrgi: --> :Amitodhana: : first wife 

:Vimala: 
note top: courtesan 


(Takkasila) -- :Mendaka: 
:Mendaka: --> :Ananda: : master 

:Ambapali: 
note top: famous curtesan 

:Visaka: --> :Vimala: : adopted daughter 

(Kapilavastu) <<location>> 

(Kapilavastu) -- abuser 

:Vimala: -- (Kapilavastu)

' froth on the river 

(Mudgala) <<location>> as gala 

budda -- gala : rashtrika 

gala -- :Vagantha:  : gambojaka 

:Vagantha: <-- :Rupasiri: : wife 

overlord --> regent : father 

:Nagamunda: --> :Amitodhana: : slave 
:Vasabha: --> :Nagamunda: :daughter 
:Vasabha: --> :Mahanama: :daughter 

' Dukkha II

:Channa: --> budda : charioteer 

' A Woman Eaten and Eaten
:Sonanda: -- (Kapilavastu) : gatekeeper 

note "widowed relatives" as w

:Tissa: .. w
:Utara: .. w

@enduml