@startuml

left to right direction
skin rose
skinparam backgroundcolor transparent
skinparam defaultfontcolor #brown
skinparam arrowcolor #blue
skinparam arrowfontcolor #forestgreen

title River East, River West

:Sloan:

:Alva:

:Lu Fang: as Fang

:Li Xinwei: as Li

Sloan -> Alva : мать


Fang -> Sloan : жених



Fang -- (свадьба)
Sloan -- (свадьба)
Alva -- (свадьба)


(свадьба) -- :Feng: : гость
(свадьба) -- :Lu: : гость
note on link : или это сам Lu Fang?



Li --> Alva : лучшая подруга

(школа) -- Alva
(школа) -- Li

:Zhang Shao: as Zhang

:Gao Xiaofan: as Gao

:Ms. Song: as Song

:Liu: as Liu

Zhang --> Alva : просто одноклассница
Zhang - (школа) : ученица

Liu -> Li : superviser

Song -- (школа) : учительница

Gao -- (школа) : ученик

:Teng Xin: as Teng
:Doggy: as Doggy

Teng --> Gao : друг
Doggy --> Gao : друг


:Ciyi: as Ciyi


(Qingdao, 1985) as Qingdao

Ciyi ->> Fang : жена

Qingdao -- Ciyi
Qingdao -- Fang
Qingdao -- Sloan

:Huang: as Huang
:Xiao Qi: as Qi
:Jim: as Jim
:Auntie Wang: as Wang
:Yu Chentian: as Yu


Huang --- Qingdao : продавец молока
Qi -- Qingdao
Qi -> Fang : выездной коллега
Wang --- Qingdao : соседка с 1 этажа

Yu --- (школа) : из параллельного класса

Jim -- Qingdao : пивовар

@enduml