@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

scale max 8192*8192

title A hiding to Nothing by Chhimi Tenduf-La
mainframe characters
legend : p. 50 (nine)

:Neja Pinto: as neja $female 
:mother-in-law: as motherInLaw <<unnamed>> $female
note right : Loku Madam?
:Ramesh: as husband  $male
:Devin: as son $male 
:Johnny Dias: as Johnny $male 

neja <-- motherInLaw : mother-in-law 
husband --> neja  : husband
neja <-- son : son 
son <-- Johnny : swimming coach 

(party) <<event>> 

party -- neja 

:Rohan Ratnasiri: as rohan $male 
rohan -- party: deputy minister 

:Cassandra: $female 
:Avanti: $female 

Cassandra -- party: school mum 
Avanti-- party: school mum 

:bucket hat man: as bucketHat <<unnamed>> $male 
:hijab woman: as hijab <<unnamed>> 


"Sri Lanka, 2007" - neja

package  "Sri Lanka, 2007"  {
    (Neja's family when 13) as family13 <<group>>


    :Appa: <<unnamed>> <<dead>> $male
    :Ammi: <<unnamed>><<dead>> $female
    :Aunty Dilly: as aunty <<mentioned>> $female
    family13 -- Appa
    family13 -- Ammi
    aunty -- family13
    neja <-- Johnny : what?

    (school) <<institution>>
    :Gamage: $female
    :Priyath: <<mentioned>> $male
    :Priyath's brother: as priyathBrother <<mentioned>> <<unnamed>> $male
    Priyath <-- priyathBrother : brother
    school -- Gamage : Principal
    Gamage --> priyathBrother : expelled
}


(kidnapping) <<event>>

(kidnapping) <-- hijab : kidnapped
(kidnapping) <-- bucketHat : kidnapped

son -- kidnapping

:Gamini: as oldman  $male

oldman - kidnapping : met after

package "Sri Lanka, Sharja and London 2009 - 2015" {
   (Ammi's parents) as najaGrands <<group>>
}

neja -- "Sri Lanka, Sharja and London 2009 - 2015"

Ammi <-- najaGrands : parents

:Durham: <<mentioned>> $male
Durham <-- husband: mentioned


@enduml