
@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

skinparam backgroundcolor #191a1c


title Фред Варгас Человек, рисующий синие круги

legend 5.2%

mainframe characters


:Матильда: as matilda $female_protagonist

:Шарль Рейе: as charles $male

:Жан-Батист "леший" Адамберг: as adamberg $male
note top: комиссар
matilda --> charles : встретила слепого

:убитый: as body $male

adamberg --> body : расследует

:Патрис Верн: as patris $male

body <-- patris : пасынок

@enduml