@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

'skinparam backgroundcolor #191a1c

skinparam packagebordercolor #888

!$pos_int = 2
!$pos_frac = 2
!$part = 1
!$chapter = 3

legend $pos_int.$pos_frac% (Chapter $part/$chapter)

mainframe **characters** John Steinbeck //**East of Eden**//


(Salinas Valley) as salinas <<location>>

package Hamiltons {
    :I: <<narrator>>
    :Samuel: $male
    :Liza: $female
}

salinas <-- Hamiltons : came about 1870

I <- Samuel : grandfather


Samuel <-- Liza : wife

:Adam Trask: as Adam $male
:Cyrus: $male

Adam -- salinas
Cyrus --> Adam : father

@enduml