@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

scale max 8192*8192


title The Safekeep by Yael van der Wouden

mainframe characters
legend
1.8% (PART I: The Netherlands, 1961 / Chapter 1)
end legend

:Isabel: as Isa $female_protagonist

(family) <<group>>

:Hendrik: $male

Isa -- family
Hendrik -- family : younger%n()brother

:Neelke: $female

Neelke --> Isa : maid

:Sebastian:  $male

Hendrik <-- Sebastian : son?

:Sebastian's mother: as sebaMother <<unnamed>>  $female

Sebastian <-- sebaMother : mother 

:Mother: <<dead>> <<unnamed>> $female
family -- Mother

:Father: <<dead>> <<unnamed>> $male
family -- Father

:Johan: $male

Johan --> Isa : visits

:Karel: $male
family -- Karel : uncle

:Karel's wife: as kareWife <<unnamed>> $female
Karel <-- kareWife

:Louis: $male
Louis -- family : elder%n()brother

@enduml