@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

scale max 8192*8192


title The Coin by Yasmin Zaher
mainframe characters


legend
7.9% (Chapter 6)
end legend

:I: $female_protagonist
(New York) as newYork <<location>>

I -- newYork : recently moved to

(Franklin school) as Franklin <<institution>>

I -- Franklin : teacher

(vacation in Havana) as Havana <<event>>

:Sasha:  $male
Havana -- Sasha
I -- Havana

:colleague: <<unnamed>>

:Aisha: $female

Franklin -- Aisha : headmistress

Aisha <-- colleague : friend
Sasha <-- colleague : colleague

(Palestine) <<location>>

Palestine -- I : left

(boys) <<group>>

Franklin -- boys : students

:Sal: $male
boys -- Sal

:Jay: $male
boys -- Jay

:Leonard: $male
boys -- Leonard

:father: <<todo>>>
:mother: <<todo>>>
:brother: <<todo>>>

@enduml