@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

scale max 8192*8192


title The Coin by Yasmin Zaher
mainframe characters


legend
15.5% (Chapter 13)
end legend

:I: $female_protagonist
(New York) as newYork <<location>>

I -- newYork : recently moved to

(Franklin school) as Franklin <<institution>>

I -- Franklin : teacher

(vacation in Havana) as Havana <<event>>

:Sasha:  $male
Havana -- Sasha
I -- Havana

:colleague: <<unnamed>>

:Aisha: $female

Franklin -- Aisha : headmistress

Aisha <-- colleague : friend
Sasha <-- colleague : colleague

(Palestine) <<location>>

Palestine -- I : left

(boys) <<group>>

Franklin -- boys : students

:Sal: $male
boys -- Sal

:Jay: $male
boys -- Jay

:Leonard: $male
boys -- Leonard

:father: <<unnamed>> <<dead>> $male
father --> I : father

:mother: <<unnamed>> <<dead>> $female
mother --> I : mother

:brother: <<unnamed>> $male
brother -> I : brother

:Leonard's mother: as leoMother <<unnamed>> $female
Leonard <-- leoMother : mother

:Carl: $male

boys - Carl

@enduml