@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

skinparam backgroundcolor #191a1c


title Fried green tomatoes at the Whistle Stop Cafe by Fannie Flagg

legend 7.1% (Chapter 8)

mainframe characters

(Whistle Stop Cafe) as cafe <<institution>>

:me: <<narrator>>

me --  cafe : next door 

:Imogene "Idgie" Threadgoode: as Idgie $female

cafe -- Idgie : owner

:Ruth Jamison: as Ruth $female

cafe -- Ruth : owner

:Sipsey: $female 

cafe --- Sipsey: cook

:Onzell: $female

cafe --- Onzell : cook

:Big George: as bigGeorge $male

cafe --- bigGeorge : cook

Onzell <- bigGeorge : husband

:Wilbur: $male

Wilbur --> me : other half

(Rose Terrace Nursing Home) as roseTerrace <<institution>>

:Big Momma: as bigMomma $female

roseTerrace -- bigMomma 

:Ed: $male

bigMomma --> Ed : mother 

:Evelyn Couch: as Evelyn $female

Ed --> Evelyn : husband 

:Mrs. Cleo Threadgoode: as Ninny $female

Ninny -- roseTerrace 

:Mrs Otis: as Otis $female

Otis -> Ninny : friend

:Essie Rue Threadgoode: as Essie $female 

Essie <.. Ninny : mentioned 

' Chapter 3

:Virginia "Ninny'" Mrs. Biddie Louise Otis: $female <<todo>>

note top: meteorite 

:Mr. Earl Adcock Sr: <<mentioned>> $male

:Bertha Vick: <<todo>>
:Harold Vick:  <<todo>>

:Leona: <<todo>>
:John Justice: <<todo>>
' Chapter 4
:Ida Simms: <<todo>>

:Cookie: <<pet>><<todo>>

:Mrs. Philbeam: <<todo>>

' Chapter 5
:Vesta: <<todo>>
:Earl Jr: <<todo>>
: Roy: <<todo>>
' Chapter 6
(hobo camp) I <<location>><<todo>>
'Jim Smokey Phillips, Elmo Inky Williams, BoWeevil Jake, Crackshot Sackett, and Chattanooga Red Barker

:Bernice:  <<todo>>

' Chapter 8

:Dr. Hadley:  <<todo>>

:Buddy:  <<todo>>

@enduml