@startuml

' while testing
!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/reading/iuml"

!include $stylePath/reading.iuml

'============== поехали ================

actor Katharina as kat <<protagonist>>

actor Hans as hans <<protagonist>>

kat --> hans
hans --> kat

'(Kranzler Cafe)  <<place>>

'Box I

:Erika Ambach: as erika

erika --> kat : mother

(Academie) as academy <<location>>

erika - academy : doctoral student

:Ingrid: as wife

wife --> hans : wife

academy - wife  : research lab

:Ludwig: as ludwig

hans <- ludwig  : son
wife <-- ludwig  : son

:Gernot: -> kat : first boyfriend

(Hungary) as hun <<location>>

:Agnes: -- hun 

:Agnes: -> erika : friend

kat -> :Christina: : childhood friend

 erika <-- :Ralph: : second husband

:Herr Sterz: as boss 

kat <-- boss : boss

kat <-- :Sibylle: : friend (gin)


@enduml