@startuml

' while testing
!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/reading/iuml"
'!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml


skinparam actor<<ex>>backgroundcolor lightcoral


'============== поехали ================
title Kairos




actor Katharina as kat <<protagonist>>

actor Hans as hans <<protagonist>>

kat --> hans
hans --> kat

'(Kranzler Cafe)  <<place>>

'Box I

:Erika Ambach: as erika

erika --> kat : mother

(Academie) as academy <<location>>

erika - academy : doctoral student

:Ingrid: as wife

wife --> hans : wife

academy - wife  : research lab

:Ludwig: as ludwig

ludwig -> hans  : son
wife <-- ludwig  : son


:Gernot: <<ex>>
:Gernot: -> kat : first boyfriend

(Hungary) as hun <<location>>

:Agnes: -- hun

:Agnes: -> erika : friend

kat -> :Christina: : childhood friend

 :Ralph: --> erika  : second husband

:Herr Sterz: as boss

kat <-- boss : boss

kat <--- :Sibylle: : friend (gin)

:Heike: --> kat : colleague

:Jens: <<ex>>

:Jens: --> kat : first kiss

kat <-- :Moritz: : guinea pig

:Phillip: <<ex>>
kat <--- :Phillip: : friend


(Cologne relatives ) as keln <<group>>

keln -- :Annie: : aunt


(Leipzig)  as leipzig <<location>>
"???" as father
kat <--- father : father
father -- leipzig


:Senta: -- keln : dog

keln -- :Katrin: : cousin
keln -- :Manfred: : uncle
kat  <-- :Emmi: : grandmother

:Katrin: <- :Christian: : fiancee

:Emmi: -->  :Annie: : mother
:Katrin: --> :Annie: : daugher
:Manfred: -> :Annie: : husband

:Emmi: ----> erika : mother

:Emmi: -- keln

:Emmi: <-- :Karl: : husband

(Stavanger) <<location>>

:Karl: --- (Stavanger) : stationed

:Gerti: -- (Stavanger)

:Peter: -- (Stavanger)

:Karl: <-- :Peter: : son

:Peter: <- :Gerti: : mother


@enduml