@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

title Heart Lamp by Banu Mushtaq
mainframe characters
legend : 7.1% (Stone Slabs for Shaista Mahal)


package "Stone Slabs for Shaista Mahal"  {

    :Zeenat: as i <<narrator>> $female_protagonist
    :Mujahid: as mujahid $male


    i <-- mujahid : home person 
    
    :Iftikhar Ahmed: as ahmed $male 
    mujahid <-- ahmed : new aquaintance 
    
    :Cheluva: $male
    
    Cheluva --> i : help? 
    
    (Ahmed family) as ahmeds <<group>> 
    ahmed -- ahmeds
    :Shaista: $female 
    Shaista -- ahmeds : wife 
    
    :Asifa: $female 
    ahmeds - Asifa : eldest daughter 
    
	 ahmeds --    :Sallu: : a child 
	 ahmeds -- :Immu:  : a child
 	ahmeds -- :Naveen:  : a child
	 ahmeds -- :Kamal:  : a child 
	
	:baby: <<unnamed>> $male 
	baby - ahmeds : newborn 
	
	 :amma: as mother <<unnamed>> <<dead>> $female 
	mother -> i : mother 

}


@enduml



