@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

title Heart Lamp by Banu Mushtaq
mainframe characters
legend : 11.8% (Fire Rain)


package "Stone Slabs for Shaista Mahal"  {

    :Zeenat: as i <<narrator>> $female_protagonist
    :Mujahid: as mujahid $male


    i <-- mujahid : home person 
    
    :Iftikhar Ahmed: as ahmed $male 
    mujahid <-- ahmed : new aquaintance 
    
    :Cheluva: $male
    
    Cheluva --> i : help? 
    
    (Ahmed family) as ahmeds <<group>> 
    ahmed -- ahmeds
    :Shaista: <<dead>> $female 
    Shaista -- ahmeds : wife 
    
    :woman: <<unnamed>> $female 
    woman -- ahmeds : new wife 
    
    :Asifa: $female 
    ahmeds - Asifa : eldest daughter 
    
	 ahmeds --    :Sallu: : a child 
	 ahmeds -- :Immu:  : a child
 	ahmeds -- :Naveen:  : a child
	 ahmeds -- :Kamal:  : a child 
	
	:baby: <<unnamed>> $male 
	baby - ahmeds : newborn 
	
	 :amma: as mother <<unnamed>> <<dead>> $female 
	mother -> i : mother 

}

package "Fire Rain" {
(mosque) <<institution>> 
:Usman Saheb: as usman $male_protagonist 

:Arifa: as arifa $female 

:Ansar: as ansar $male

mosque -- usman : mutawali 
usman <-- arifa : wife 

usman <- ansar : son 
arifa <- ansar : son 

:Jameela: as jameela $female 
:husband: as jameelaHusband <<unnamed>> $male

jameela -> usman : youngest sister 
jameelaHusband --> jameela 

:Sakeena: as sakeena $female
:Syed Abrar: as sakeenaCompany $male 

usman <- sakeena : eldest sister 
sakeena <-- sakeenaCompany : son 

:Dawood: $male 

Dawood --> usman : right-hand man 

(supplicants) <<group>> 

:Saabjaan: $male 

usman -- supplicants : sees 

supplicants -- Saabjaan : daughter's wedding 

sakeena -- supplicants : son's employment 
}


@enduml



