@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml
title The Vegetarian
mainframe characters


:Mr Cheong: as narrator <<protagonist>>

:Yeong-hue: as vegetarian
note top : The Vegetarian

vegetarian --> narrator : wife

:In-hye: as sister

sister --> vegetarian : sister
'sister --> narrator : sister-in-law

:Yeong-ho: as brother

brother --> vegetarian : yoгnger brother 


:Ji-woo: as nephew 

nephew --> sister : son


@enduml
