@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml
title The Vegetarian
mainframe characters

legend : only named characters shown (except brother-in-law)


:Mr Cheong: as narrator <<protagonist>>
note top : Part I

:Yeong-hue: as vegetarian
note top : The Vegetarian

vegetarian --> narrator : wife

:In-hye: as sister <<protagonist>>
note top : Part III

sister --> vegetarian : sister
'sister --> narrator : sister-in-law

:Yeong-ho: as brother

brother --> vegetarian : yonger brother


:Ji-woo: as nephew 

nephew --> sister : son 

' Mongolian mark

(Studio) as studio <<location>>
:brother-in-law: as he <<protagonist>>
nephew --> he : son
note top : Part II

sister --> he : wife 
he -- studio 
studio -- :J: 

(another studio) as mstudio <<location>> 

he -- mstudio 

:M: -- mstudio : owner

he <-- :M: : friend 

vegetarian -- mstudio
mstudio -- :J:

:P:<<ex>>

:P: --> he

(Kim family) as family <<group>>

family -- sister
family -- brother

' Flaming trees

(Ch’ukseong Psychiatric Hospital) <<istitution>> as hospital
"Dr. Park In-ho" as doctor

vegetarian --- hospital : patient

hospital -- doctor : doctor

@enduml
