@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

scale max 8192*8192

title The Hallmarked man
mainframe characters
legend : 4.7% (Part One / 6)


:Cormoran Blue Strike: as strike $male_protagonist
:Robin Elacott: as robin $female_protagonist

(Agency) <<institution>>

'Strike and Ellacott Detective
strike -- (Agency) : owner & founder
robin -- (Agency) : partner

:Ryan Murphy: as murphy $male
murphy --> robin : boyfriend

:Lucy: $female
Lucy --> strike : sister 
:Ted: <<dead>> $male 
Ted --> strike : uncle 

:Decima Mullins: as decima $female
Agency -- decima : client 

(Delamore Lodge) as delamore <<location>> 
decima -- delamore : hides in

:Valentine Longcaster: as Valentine <<mentioned>> $male
decima <-- Valentine : brother 

 :Charlotte Campbell: as Charlotte <<dead>> <<mentioned>> $female 

strike <-- Charlotte : <<ex>>

 :Sacha Legard: as Sacha $male 
 
 Charlotte <-- Sacha : half brother

 :William Wright: as body <<dead>> $male
 
 decima --> body : whants to know 

 (Ramsay Silver) as silver <<institution>>

 body -- silver : worked at

(The Happy Carrot) as carrot <<institution>>

carrot -- decima : owns

:Gayle: $female
Gayle -- carrot : "maître d’"


 :Jason Knowles: as Jason $male
 body ..> Jason  : falsely identified as

 :Sir Daniel Gayle: as sirDaniel $male
sirDaniel <-- Gayle : daughter

 :Lion: $male
 Lion --> decima : baby

 :Jeff Whittaker: as Whittaker $male
 :Leda: <<dead>> $female
  Leda --> strike : mother
  Whittaker --> Leda : murdered

:Rupert Peter Bernard Christian Fleetwood: as rupe  $male
rupe -> decima : husband(?)
rupe ..> body : suspected by Decima
Sacha --> rupe: cousin 

:Veronica: <<dead>> $female
:Peter:  <<dead>> $male

Veronica --> rupe : mother
Peter --> rupe : father

:Zac: $male

rupe <-- Zac : housemate
:Dredge: $male

Zac --> Dredge : owed

:Anjelica Wallner: as aunt $female 

rupe <-- aunt : aunt 

:Linda: $female 
Linda --> robin : mother 

:Mr Butler: as mrButler $male
mrButler --> robin : Surgeon 
:Tara: $female 
Tara --> Charlotte: mother 
:Dino: $male 
Dino --> Valentine: father 
:Ned Legard: $male 
note right: второй отчим Шарлотты, отец актера, дядя руперта 
 
 :Kim Cochran: as Kim $female 
 Agency -- Kim : latest hire 
 (Plug) 
 Agency -- Plug : side case 
 note right: дядя нанял маму доят, есть сын 
 :Dave Polworth: 
@enduml