@startuml

left to right direction
skin rose
skinparam backgroundcolor seashell
skinparam defaultfontcolor #brown
skinparam arrowcolor #blue
skinparam arrowfontcolor #forestgreen

title River East, River West

:Sloan: #pink

:Alva: #pink

:Lu Fang: as Fang #pink

:Li Xinwei: as Li

Sloan -> Alva : мать


Fang -> Sloan : в итоге муж



Fang -- (свадьба) : жених
Sloan -- (свадьба) : невеста
Alva -- (свадьба)


(свадьба) -- :Feng: : гость
(свадьба) -- :Lu: : гость
note on link : или это сам Lu Fang?



Li --> Alva : лучшая подруга

(школа) -- Alva : ответственная за ДЗ
(школа) -- Li

:Zhang Shao: as Zhang

:Gao Xiaofan: as Gao

:Ms. Song: as Song

:Liu: as Liu

Zhang -- (школа) : одноклассница

Liu -> Li : superviser

Song -- (школа) : учительница

Gao -- (школа) : ученик

:Teng Xin: as Teng
:Doggy: as Doggy

Teng --> Gao : друг
Doggy --> Gao : друг


:Ciyi: as Ciyi


(Qingdao, 1985) as Qingdao

Ciyi ->> Fang : жена

Qingdao -- Ciyi
Qingdao -- Fang
Qingdao -- Sloan

:Huang: as Huang
:Xiao Qi: as Qi
:Jim: as Jim
:Auntie Wang: as Wang
:Yu Chentian: as Yu


Huang -- Qingdao : продавец молока
Qi -- Qingdao
Qi -> Fang : выездной коллега
Wang -- Qingdao : соседка с 1 этажа

Yu --- (школа) : из параллельного класса

Jim -- Qingdao : пивовар

Fang --> :Lu Min: : сын
Ciyi --> :Lu Min: : сын

' новая школа Альвы

(новая школа) as new_school

Alva -- new_school

:Ms Steward: as Steward

new_school -- Steward : учительница

:Zoey: as Zoey

Alva --> Zoey : новая подруга

Zoey -- new_school

(Дом Зои) as zoey_home

Zoey -- zoey_home

new_school -- :Ashley:  :одноклассница

:Jiyoon: as korean <<кореянка>>

new_school -- korean

:Feng: as Feng_driver
:Julia: as Julia
:Girlie: as girlie

Julia --> Zoey : мать

Julia -- zoey_home

zoey_home -- Feng_driver : водитель
zoey_home -- girlie : служанка

korean -> Ashley : подруга

:Daniel: as Daniel

Daniel -- zoey_home
Daniel --> Zoey : отец
Daniel --> Julia : муж

@enduml