@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

title James
mainframe characters
legend : 98.2% (Chapter III-10)


:James: as jim  <<narrator>> $male_protagonist

:Miss Watson: as owner $female

owner -->  jim : master

:Tom Sawyer: as tom $male
:Huckleberry Finn: as huck $male

tom <--> huck : friends

:Sadie: as sadie <<slave>> $female

(Jim's family) as family <<group>>

family -- jim
family -- sadie : wife

:Elizabeth: as lizzie <<slave>> $female

lizzie -- family : daughter

:Judge Thatcher: as judge $male

:Albert: as albert <<slave>> $male


(Fire outside) as fire <<event>>

fire -- jim

albert -- fire : called Jim

:Doris: as doris <<slave>> $male

doris -- fire

:Old Luke: as luke <<slave>> $male

luke -- fire

:Skinny: as skinny <<slave>> $male
skinny - fire

(language lesson) as lesson <<event>>

lesson --- jim : gave

lesson -- lizzie

:Virgil: as student1 <<slave>> $male
:February: as student2 <<slave>> $female
:January: as student3 <<slave>>
:Rachel: as student4 <<slave>> $female
:Glory: as student5 <<slave>> $female

lesson -- student1
lesson -- student2
lesson - student3
student4 -- lesson
student5 -- lesson

:Pap: as father <<unnamed>> <<dead>>$male

huck <-- father : legally father

:widow Douglas: as widow $female

:Bessie: as bekkie $female

judge <-- bekkie : daughter

'(whites) <<group>>
'(slaves) <<group>>

huck <--> jim : on the run together

:Aunt Polly: as polly $female

tom <-- polly : aunt

:April: as april <<slave>>
:Cotton: as cotton <<slave>>

(old slaves) as old <<group>>

jim --- old : stolen firewood for

old -- april
old -- cotton


(Four black men) as four <<group>>

jim -- four : met in Illinois

:Young George: as muscular <<slave>>  $male
:Old George: as oldest <<slave>>  $male
:Josiah: as big  <<slave>> $male
:Pierre: as squintyEyes <<slave>>  $male

four -- muscular
four -- oldest
four -- big
four -- squintyEyes

(Grangerfords) as grangerfords <<group>>
(Shepherdsons) as shepherdsons <<group>>

muscular -- grangerfords : mentioned
muscular -- shepherdsons : mentioned

grangerfords <-> shepherdsons : hate

master as master <<unnamed>>

muscular <-- master : stole pencil from

:Harney: as fiance $male
:Sophia: as bride $female

shepherdsons -- fiance
grangerfords -- bride
bride  <-> fiance

:Papa: as papa $male

grangerfords -- papa

:"Duke" Bridgewater: as duke


huck --> duke : saved

widow <--> owner : sisters

:"Dauphin": as dauphin

huck --> dauphin : saved

:Easter: as blacksmith <<slave>> $male

jim <--- blacksmith : chained up

:Mr Wiley: as wiley $male

blacksmith <-- wiley : owner

:Daniel Decatur Emmett: as emmet $male

wiley --> emmet : bought Jim

(Virginia Minstrels) as minstrels <<group>>

emmet -- minstrels : leader

:Cassidy: as cassidy $male

minstrels -- cassidy : trombone

:Norman: as norman $male
minstrels -- norman : drums

:just Polly: as spectator

minstrels - spectator : spectator

:fat all white man: as pollyFather <<unnamed>> $male
spectator <-- pollyFather : father

:Big Mike: as clarinet $male

clarinet -- minstrels : clarinet

:good lawman: as nephew <<unnamed>> $male

pollyFather <-- nephew : nephew

(Bluebird Hole) as hole <<location>>

:Frank McHart: as constable $male

hole -- constable : constable

:Old Man Henderson: as henderson $male

hole -- henderson : holds sawmill

:Luke: as anotherLuke <<slave>> $male
:Sammy: as sammy <<slave>> <<dead>> $female
:Rainbo: as rainbow <<slave>> $male

henderson --> anotherLuke : owns
henderson --> sammy : owns
henderson --> rainbow : owns


(Steamboat) as boat <<location>><<institution>>
:Corey: $male
:Brock: as brock <<slave>> $male

boat -- brock : coal guy
brock <-- Corey : supposedly master

:Katie: as katie <<slave>> $female
:Hopkins: as hopkins <<dead>> $male

katie <- hopkins  : raped

jim --> hopkins : killed

(Corn field) as cornfield <<location>>

:April: as april2 <<slave>> $male
:Holly: as holly <<slave>> $female

cornfield -- april2
cornfield -- holly

(Graham's place men) as men <<location>>

:Morris: <<slave>> $male
:Harvey: <<slave>> $male
:Llewelyn: <<slave>> $male
:Buck: <<slave>> $male

Morris -- men
Harvey -- men
men -- Llewelyn
men -- Buck

@enduml