@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"
!include $stylePath/reading.iuml

title James
mainframe characters
legend : 27.7% (Chapter 14)


:James: as jim  <<narrator>> $male_protagonist

:Miss Watson: as owner $female

owner -->  jim : master

:Tom Sawyer: as tom $male
:Huckleberry Finn: as huck $male

tom <--> huck : friends

:Sadie: as sadie <<slave>> $female

(Jim's family) as family <<group>>

jim -- family
family -- sadie : wife

:Elizabeth: as lizzie <<slave>> $female

family -- lizzie : daughter

:Judge Thatcher: as judge $male

:Albert: as albert <<slave>> $male


(Fire outside) as fire <<event>>

fire -- jim

albert -- fire : called Jim

:Doris: as doris <<slave>> $male

doris -- fire

:Old Luke: as luke <<slave>> $male

luke -- fire

:Skinny: as skinny <<slave>> $male
fire - skinny

(language lesson) as lesson <<event>>

jim -- lesson : gave

lesson -- lizzie

:Virgil: as student1 <<slave>> $male
:February: as student2 <<slave>> $female
:January: as student3 <<slave>>
:Rachel: as student4 <<slave>> $female
:Glory: as student5 <<slave>> $female

lesson -- student1
lesson -- student2
lesson - student3
student4 -- lesson
student5 -- lesson

:Pap: as father <<unnamed>> <<dead>>$male

huck <-- father : father

:widow Douglas: as widow $female

:Bessie: as bekkie $female

judge <-- bekkie : daughter

'(whites) <<group>>
'(slaves) <<group>>

huck <--> jim : on the run together

:Polly: as polly $female

tom <-- polly : aunt

:April: as april <<slave>>
:Cotton: as cotton <<slave>>

(old slaves) as old <<group>>

jim -- old : stolen firewood

april -- old
old - cotton


(Four black men) as four <<group>>

jim -- four : met in Illinois

:Young George: as muscular  $male
:Old George: as oldest  $male
:Josiah: as big  $male
:Pierre: as squintyEyes  $male

four -- muscular
four -- oldest
four -- big
four -- squintyEyes


@enduml