@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml

title Butter
mainframe characters 

:Rika Machida: as rika $female_protagonist 
:Reiko: as reiko $female 

reiko --> rika: friend 

(Oyamadai) <<location>>
Oyamadai -- reiko: lived previously 

:Ryōsuke: as husband $male 
husband --> reiko : husband 

:Makoto Fujimura: as makoto $male 

rika <-- makoto : boyfriend 

Misaki $female 
Misaki -> rika : mother 

:Manaki Kajii: as manaki <<suspect>> $female


(Le Salon de Miyuko) as salon <<insitution>>
:Miyuko Sasazuka: as miyuko $female

(French Restaurant Balzac) as balzac <<insitution>>

miyuko -- salon : founder

:Mr Sasazuka: as  sasazuka $male

sasazuka --> miyuko : husband
sasazuka -- balzac : owner

manaki - salon : student

rika -> manaki : //working on?//

:Yoshinori Shinoi: $male
note top: news agency editor

(Shūmei Weekly) as newspaper <<insitution>>
rika --> newspaper : journalist
newspaper -- Kitamura: junior member of stuff
newspaper - makoto

:Yū Uchimura:

@enduml