@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml
title The Story of a Brief Marriage
mainframe characters


:Dineshkanthan: as dinesh <<protagonist>> 

:Somasundaram:

:Ganga:

:Ganga: --> :Somasundaram: : daughter


@enduml