@startuml

'left to right direction
skin rose
skinparam backgroundcolor seashell


' Chapter 1

:Fetter: as fetter #pink

:Mother-of-Glory: as mother

:the Perfect and Kind: as father


mother --> fetter : мать
father --> fetter : отец

(Acusdab) -- mother
(Acusdab)-- fetter

' Chapter 3
:Hejmen: as hejmen

hejmen --> fetter : date 
@enduml
