@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/reading/iuml"

!include $stylePath/reading.iuml

skinparam actor<<unnamed>>fontsize 18
skinparam actor<<unnamed>>fontcolor forestgreen

title Женщина в клетке
mainframe characters
legend : 9.6%

:Меретта Люнггор: as caged  $female_protagonist

:Карл Мёрк: as he $male_protagonist

:Вигга: as wife $female
wife --> he : в процессе развода

:Харди Хеннингсен: as paralized $male
note right: парализованный

:Анкер: as anker <<dead>> $male

(Перестрелка) as shooting <<event>>

anker -- shooting
shooting -- paralized
shooting -- he

:Таге Баггенсен: as baggensen $male

:Марианна Кох: as secretary $female

caged <-- secretary : бывшая секретарша

baggensen <-- secretary : сватала

(Отдел по расследованию убийств) as murders <<institution>>

:Маркус Якобсен: as moira $male

murders -- moira : начальник


:Ларс Бьёрн: as lars $male

moira <-- lars : заместитель

:Пив Вестергор: as vestegor $female
note right: Датская партия, докладчик по правовой политике

(Отдел Q) as q <<institution>>

'murders o- q  : административно подчиняется
q --o murders  : административно подчиняется
he -- q

:Георг Мадсен: as body <<dead>> $male
body -- shooting : труп

:Уффе: as brother $male

brother --> caged : брат

:домработница: as help <<unnamed>> $female
help --> caged : домработница

:любовник: as new <<unnamed>> $male

new --> wife : новый

:Мортен Холланн: as tenant $male


:Йеспер: as stepson $male


(дом в Рённехольте) as home <<location>>

home -- he : живет
stepson --> home : пасынок
tenant --> home : жилец

(Оперативная группа) as group <<institution>>

murders o- group
'group -o murders

:Вигго Бринк: as viggo $male
:Питер Вестевиг: as piter $male

viggo -- group : начальник
group -- piter

:девушка: as police_secretary <<unnamed>> $female
moira <-- police_secretary : секретарша

:Курт Хансен: as mp $male
note right:  Консервативная партия, бывший вице-комиссар

(Фолькетинг) as volketing <<institution>>

volketing -- mp
volketing -- vestegor

volketing -- caged

:Сёс Норуп: as secretary2 $female

caged <-- secretary2 : новая секретарша
volketing -- baggensen

:Дэниель Хейл: $male

paralized -- q

:Лиза: as mediumSecretary1 $female
:темноволосая: as mediumSecretary2 <<unnamed>> $female

q .. mediumSecretary1 : посредник
q .. mediumSecretary2 : посредник

mediumSecretary1 -- murders : секретарша
mediumSecretary2 -- murders : секретарша


@enduml
