@startuml

!$stylePath = "https://raw.githubusercontent.com/olek3/plantuml-includes/refs/heads/main/iuml"

!include $stylePath/reading.iuml
title Сердце Пармы 
mainframe characters


:Асыка: as prince $male_protagonist 
:Юмшан: as yumshan $male

yumshan --> prince : сын 

(Мертвая Парма) as deadParma <<location>>
(поход в мертвую Парму) as gathering <<event>>

gathering --> deadParma : туда
prince -- gathering

:Нята: as nyata
nyata --> prince: конь 

(Вышкар) as shamanCity <<institution>>

shamanCity -- deadParma   

:Верховный шаман: as pam $male

pam -- shamanCity: Верховный шаман 

(Русская станица) as rusStan <<event>> 

deadParma -- rusStan 

:Демьян Ухват: as demyan $male_protagonist 


:Васька Калина: as conductor $male 

rusStan -- conductor: проводник

(новгородцы) as neapolitans <<group>> 

demyan - neapolitans: предводитель 

rusStan -- neapolitans 

(ратники Полюда) as poluds <<group>> 
rusStan -- poluds 

:Полюд: as polud $male 

poluds <.. polud: послал

:Питирим: as bishop $male

:дядя Ваня: as uncleVanya $male 
:Ванюха Окунь: as perch $male

:Ивашка Меньшой: as small $male

poluds -- uncleVanya 
poluds -- perch
poluds -- small

:Семка: as messenger $male

neapolitans -- messenger: самый младший, выжил

:Ероха Смыка: as erokha $male 
neapolitans -- erokha: давний напарник 

conductor <.... bishop: послал

(Чердынь) as cherdyn <<location>> 

bishop -- cherdyn  : епископ

(Усть-Вым) as ustVym <<location>> 
:Ермолай: as ermolay $male_protagonist 

ustVym - ermolay: князь

:Пишка: as pishka $male 
pishka -- neapolitans: выжил 

:Гаврила: as gavrila $male
gavrila -- neapolitans 

:Михаил: as misha $male_protagonist
misha --> ermolay: старший сын
(Пермь Великая) as greatParma <<location>> 
misha -- greatParma: князь

:Васька: as vaska $male

vaska --> ermolay: сын

:Айчейль: as aycheyl $female 

aycheyl ---> misha : нянька
aycheyl ---> vaska : нянька

:Степан Рогожа: as centurion $male
ermolay <-- centurion: сотник

(Вычегда) as vychegda <<location>> 
(Ульяновский монастырь) as monastery <<instutution>> 

vychegda -- monastery 

:отец Иона: as iona $male

monastery -- iona: настоятель 

:Лукашка: as luka $male

luka --> ermolay: кухонный мужик
:Танег: as taneg $male 

taneg -- cherdyn : князь

ermolay ..> taneg: споил 

:Тичерть: as tichert $female 
taneg <-- tichert : дочь

prince ---> aycheyl: муж 

:Ничейка: as noones $male 

bishop <--- noones: информатор

(Анфаловский городок) as anfalov <<location>> 
:Кривонос: as esaul $male 
anfalov -- esaul: есаул 

:Савела: as horseman $male 
horseman --> ermolay: конюх

:Бурмот: as burmot $male 
polud <-- burmot: //ученик//

(Афкуль) as afkul <<location>>
:Мансур: as mansur $male

afkul -- mansur : шибан

:Семка-Дура: as messenger $male

messenger <.. mansur : перехватил
messenger <.. misha : послал с ябедой

:Исур: as isur $male

mansur <-- isur : сын

:Солэ: as sole $female
sole ..> conductor : спасла


@enduml